export default {
    GET_ALL_DATA_REQUEST: 'GET_ALL_DATA_REQUEST',
    GET_ALL_DATA_SUCCESS: 'GET_ALL_DATA_SUCCESS',
    GET_ALL_DATA_ERROR: 'GET_ALL_DATA_ERROR',

    ADD_CATEGORY: 'ADD_CATEGORY'
};
