export default {
    GET_ALL_DATA_REQUEST: 'GET_ALL_DATA_REQUEST',
    GET_ALL_DATA_SUCCESS: 'GET_ALL_DATA_SUCCESS',
    GET_ALL_DATA_ERROR: 'GET_ALL_DATA_ERROR',

    GET_SINGLE_DATA: 'GET_SINGLE_DATA',
    ADD_SINGLE_DATA: 'ADD_SINGLE_DATA',
    CHANGE_SINGLE_DATA: 'CHANGE_SINGLE_DATA'
};
